spring.datasource.url=jdbc:postgresql://localhost:5433/week05_lab01
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true

spring.application.name=KINETICA